"""
HealthNav AI – Symptom RAG Index Builder (Multi-Chunk Embedding)
================================================================

HIGH-LEVEL GOAL
---------------
This script takes the *structured* symptom JSON objects produced by
`symptom_structurer.py` and builds a **RAG-ready vector index** using ChromaDB.

Input  (already generated by symptom_structurer.py):
    outputs/tmt_symptoms_structured.jsonl
    → one JSON line per symptom, e.g.:

    {
      "symptom": "COUGH",
      "one_sentence_definition": "...",
      "essential_questions": [...],
      "system_differentials": [...],
      "possible_causes": [...],
      "red_flags": [...],
      "when_to_refer_emergency": [...],
      "key_examination_findings": [...],
      "useful_diagnostic_tests": [...],
      "triage_logic": "...",
      "specialty_routing": [...],
      "rag_summary": "..."
    }

Output:
    A **Chroma persistent collection** where EACH row is a *small clinical chunk*:
    - “COUGH – DEFINITION”
    - “COUGH – RED FLAGS”
    - “COUGH – ESSENTIAL QUESTIONS”
    - “CHEST PAIN – TRIAGE LOGIC”
    - etc.

    Each chunk has:
      - `id`         → unique string like "cough::red_flags"
      - `document`   → short text block (human-readable clinical content)
      - `embedding`  → vector from OpenAI embeddings
      - `metadata`   → { symptom, section, source, etc. }

WHY WE SPLIT EACH SYMPTOM INTO MULTIPLE CHUNKS
----------------------------------------------
We DO NOT store each symptom as one giant blob of text.

Instead, we split into **focused pieces**:
- definition
- essential questions
- red flags
- triage logic
- diagnostic tests
- specialty routing
- etc.

WHY?

Because at query time (triage), the retrieval step is *dumb*:
it only returns vectors that are **closest in meaning** to the user’s question.

Example:
    User: "I have chest pain going to my left arm, nausea, and sweating."

We want retrieval to pull:
    - CHEST PAIN – RED FLAGS
    - CHEST PAIN – TRIAGE LOGIC
    - possibly ACS-specific chunks

We *don’t* want to dilute that with 800 words of generic prose.

Multi-chunk embedding = higher recall of the *right* clinical facts:
- exact red-flag lists
- specific triage thresholds
- emergency criteria
- and relevant specialty routing

This is crucial for **safety, explainability, and correct triage**.

WHAT THIS SCRIPT DOES STEP-BY-STEP
----------------------------------
1. Load `.env` to get `OPENAI_API_KEY`.
2. Load all structured symptom JSON objects from `tmt_symptoms_structured.jsonl`.
3. For each symptom JSON, build multiple **chunk strings**, e.g.:

   - "COUGH — DEFINITION: ..."
   - "COUGH — ESSENTIAL QUESTIONS:\n- ...\n- ..."
   - "COUGH — RED FLAGS:\n- ..."

4. For each chunk we create:
   - `id`         : stable unique identifier
   - `text`       : human readable chunk text
   - `metadata`   : {symptom, section, chunk_type, source="TMT_2022_CH2"}

5. Call OpenAI **embeddings API** once for the whole batch of chunk texts.
6. Store all chunks in a **Chroma persistent collection** called `"symptom_chunks"`.

After this, any triage agent can:
- embed the user input
- query Chroma for top-k nearest chunks
- feed those chunks into the LLM as context
- reason in a grounded, textbook-anchored way

You can think of this script as:
    “Compile my structured medical knowledge into a search-optimized RAG brain.”
"""
"""
===============================
HealthNav AI – RAG Architecture
===============================

This script is the second major stage in the HealthNav AI Clinical Reasoning Engine.
It transforms our *structured medical knowledge* into a **search-optimized vector index**
that powers real-time triage, red-flag detection, and symptom reasoning.

This comment block summarizes the entire logic and decisions that led to this system.

---------------------------------------------------------------------------
1. WHERE THIS DATA CAME FROM – THE STRUCTURING PHASE
---------------------------------------------------------------------------
Before this script runs, we execute `symptom_structurer.py`.

That earlier script:
- Extracts raw clinical text from Chapter 2 of *Current Medical Diagnosis & Treatment* (TMT 2022)
- Sends each symptom’s raw prose to GPT-4 using a deterministic prompt
- Produces a *structured JSON object* per symptom, including fields like:
    • one_sentence_definition
    • essential_questions
    • system_differentials
    • red_flags
    • possible_causes
    • emergency criteria
    • key_exam_findings
    • diagnostic tests
    • triage_logic
    • specialty_routing
    • rag_summary

This structured file lives at:
    outputs/tmt_symptoms_structured.jsonl

We currently have **13 symptoms**, but each symptom contains **10–12 medical subsections**.

These structured objects are the foundation of our knowledge graph.

---------------------------------------------------------------------------
2. WHY WE DO NOT EMBED ENTIRE SYMPTOMS AS ONE CHUNK
---------------------------------------------------------------------------
Raw clinical blocks are long (200–800 words).  
If we put each symptom as *one giant embedding*, retrieval would fail.

Example:
User says:
    “Chest pain that radiates to my left arm with sweating”

We want retrieval to hit:
    CHEST PAIN – RED FLAGS
    CHEST PAIN – WHEN TO REFER EMERGENCY
    CHEST PAIN – TRIAGE LOGIC

But if you embed entire symptoms:
- “Chest pain” becomes a HUGE blob of text
- The red flags are diluted among irrelevant paragraphs
- Vector similarity becomes noisy and loses precision

This is unsafe and leads to bad triage.

**RAG must retrieve *specific clinical units*, not entire chapters.**

Therefore, we use **multi-chunk embedding**.

---------------------------------------------------------------------------
3. HOW MULTI-CHUNK EMBEDDING WORKS
---------------------------------------------------------------------------
For each symptom, we split its structured fields into multiple chunks.
For example, for “COUGH” we create chunks like:

- COUGH::definition
- COUGH::essential_questions
- COUGH::possible_causes
- COUGH::system_differentials
- COUGH::red_flags
- COUGH::triage_logic
- COUGH::specialty_routing
- COUGH::rag_summary
- …

Each chunk looks like this internally:

    {
      "id": "cough::red_flags",
      "text": "Symptom: COUGH\nSection: RED FLAGS\n\n- Hemoptysis\n- Weight loss\n...",
      "metadata": {
          "symptom": "COUGH",
          "section": "red_flags",
          "title": "RED FLAGS",
          "source": "TMT_2022_CH2",
          "type": "symptom_chunk"
      }
    }

This gives us:
- **Fine-grained clinical recall**
- **Better safety**
- **Better explainability**
- **Better grounding for the LLM**

Across 13 symptoms, we produced **143 total chunks**.

---------------------------------------------------------------------------
4. WHY WE USE OPENAI EMBEDDINGS (text-embedding-3-small)
---------------------------------------------------------------------------
We explicitly generate embeddings using:

    model="text-embedding-3-small"

Reasons:
- Fast
- Cheap
- Excellent for retrieval
- Dimension ~1536 (perfect balance for clinical domain)
- Deterministic and reproducible

We do NOT let Chroma embed things automatically.
We explicitly provide vectors for full control and model transparency.

---------------------------------------------------------------------------
5. WHY WE USE CHROMADB (PERSISTENT VECTOR STORE)
---------------------------------------------------------------------------
Chroma provides:
- Local persistent storage (survives restarts)
- Fast vector similarity search
- Metadata filtering
- Lightweight, perfect for an MVP
- Easy migration to cloud vector DB later (Pinecone, Weaviate, Qdrant)

We create a persistent DB in:
    chroma_symptoms/

Inside this DB, the collection `"symptom_chunks"` contains all embedded chunks.

Chroma stores:
- embeddings (float vectors)
- documents (the short clinical text)
- metadata (symptom, section, title, source)

---------------------------------------------------------------------------
6. WHAT WE BUILT (RESULT)
---------------------------------------------------------------------------
Running this script produced:

    [+] Loaded 13 structured symptom records.
    [+] Built 143 chunks from 13 symptoms.
    [+] Embedding all chunks with OpenAI...
    [+] Embedding complete.
    [+] Created Chroma collection: symptom_chunks
    [✓] Indexed 143 chunks into collection 'symptom_chunks'.

This means:
You now have a **searchable medical knowledge vector engine**.

---------------------------------------------------------------------------
7. HOW TRIAGE WILL USE THIS (NEXT SCRIPT)
---------------------------------------------------------------------------
The next step is to implement the RAG query engine, for example:

    User input → embedding → search top-k chunks → GPT reasoning

If user says:

    “I have chest pain going to my left arm with sweating.”

The pipeline will retrieve:
- CHEST PAIN – RED FLAGS
- CHEST PAIN – TRIAGE LOGIC
- CHEST PAIN – POSSIBLE CAUSES
- CHEST PAIN – EMERGENCY CRITERIA

These chunks get fed into GPT-4o as grounding context, leading to a safe,
clinically anchored triage response.

This is EXACTLY how professional medical LLM products (Avey, Hippocratic,
Med-PaLM 2) implement clinical retrieval.

---------------------------------------------------------------------------
SUMMARY
---------------------------------------------------------------------------
This script converts structured symptom knowledge into a **RAG-optimized vector database**
with multi-chunk embeddings, persistent storage, and metadata-rich entries.

It is the core engine that will power:
- Intelligent triage
- Red-flag detection
- Emergency escalation
- Specialty routing
- Clinically grounded reasoning

This file is the “compiler” that turns medical knowledge into the neural search
brain of the HealthNav AI system.
"""

import os
import json
from typing import List, Dict, Any

from dotenv import load_dotenv
from openai import OpenAI
import chromadb
import traceback, sys
sys.excepthook = lambda t,v,tb: traceback.print_exception(t,v,tb)

# ============================================================
# ENV + PATH CONFIG
# ============================================================

# Load environment variables so OPENAI_API_KEY is available
load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Input: output of symptom_structurer.py
STRUCTURED_PATH = os.path.join(BASE_DIR, "outputs", "tmt_symptoms_structured.jsonl")

# Where Chroma will store its persistent database on disk
CHROMA_DIR = os.path.join(BASE_DIR, "chroma_symptoms")

# Name of the collection we'll store chunks in
COLLECTION_NAME = "symptom_chunks"

# Initialize OpenAI client (uses OPENAI_API_KEY from env)
client = OpenAI()

# Initialize Chroma persistent client
chroma_client = chromadb.PersistentClient(path=CHROMA_DIR)


# ============================================================
# HELPER: LOAD STRUCTURED SYMPTOMS
# ============================================================

def load_structured_symptoms(path: str) -> List[Dict[str, Any]]:
    """
    Reads the JSONL file created by symptom_structurer.py
    and returns a list of Python dicts.

    Each line is a complete symptom object.
    """
    records = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                records.append(obj)
            except json.JSONDecodeError:
                print(f"[WARN] Skipping invalid JSON line: {line[:80]}...")
    print(f"[+] Loaded {len(records)} structured symptom records.")
    return records


# ============================================================
# HELPER: BUILD TEXT CHUNKS FROM ONE SYMPTOM OBJECT
# ============================================================

def build_chunks_for_symptom(symptom_obj: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Given a single structured symptom dict, build multiple *chunk* dicts.

    Each chunk dict has:
        - id:       str (unique, stable identifier)
        - text:     str (what we will embed & store as `document`)
        - metadata: dict (extra info – used for filtering / debugging / interpretability)

    Example chunk:
        {
          "id": "COUGH::red_flags",
          "text": "Symptom: COUGH\nSection: RED FLAGS\n\n- Hemoptysis\n- Weight loss\n...",
          "metadata": {
            "symptom": "COUGH",
            "section": "red_flags",
            "source": "TMT_2022_CH2",
            "type": "symptom_chunk"
          }
        }
    """
    symptom_name = symptom_obj.get("symptom", "").strip() or "UNKNOWN"

    # Helper to slugify symptom names for IDs (COUGH → cough)
    symptom_slug = symptom_name.lower().replace(" ", "_")

    chunks: List[Dict[str, Any]] = []

    # Utility to add a chunk only if there is content
    def add_chunk(section_key: str, title: str, value: Any):
        """
        section_key : internal key, used in IDs and metadata (e.g. 'red_flags')
        title       : human readable title (e.g. 'RED FLAGS')
        value       : could be str or list[str]
        """
        # Normalize content to a string
        if isinstance(value, str):
            content = value.strip()
        elif isinstance(value, list):
            # Join list into bullet points
            content = "\n".join(f"- {item}" for item in value if str(item).strip())
        else:
            content = ""

        if not content:
            return  # skip empty sections entirely

        chunk_id = f"{symptom_slug}::{section_key}"

        text = f"Symptom: {symptom_name}\nSection: {title}\n\n{content}"

        metadata = {
            "symptom": symptom_name,
            "section": section_key,
            "title": title,
            "source": "TMT_2022_CH2",
            "type": "symptom_chunk",
        }

        chunks.append({
            "id": chunk_id,
            "text": text,
            "metadata": metadata,
        })

    # Now map each field in the symptom object to a chunk
    add_chunk("definition", "DEFINITION", symptom_obj.get("one_sentence_definition", ""))

    add_chunk("essential_questions", "ESSENTIAL QUESTIONS", symptom_obj.get("essential_questions", []))

    add_chunk("system_differentials", "SYSTEM DIFFERENTIALS", symptom_obj.get("system_differentials", []))

    add_chunk("possible_causes", "POSSIBLE CAUSES", symptom_obj.get("possible_causes", []))

    add_chunk("red_flags", "RED FLAGS", symptom_obj.get("red_flags", []))

    add_chunk("when_to_refer_emergency", "WHEN TO REFER - EMERGENCY", symptom_obj.get("when_to_refer_emergency", []))

    add_chunk("key_examination_findings", "KEY EXAMINATION FINDINGS", symptom_obj.get("key_examination_findings", []))

    add_chunk("useful_diagnostic_tests", "USEFUL DIAGNOSTIC TESTS", symptom_obj.get("useful_diagnostic_tests", []))

    add_chunk("triage_logic", "TRIAGE LOGIC", symptom_obj.get("triage_logic", ""))

    add_chunk("specialty_routing", "SPECIALTY ROUTING", symptom_obj.get("specialty_routing", []))

    add_chunk("rag_summary", "RAG SUMMARY", symptom_obj.get("rag_summary", ""))

    return chunks


# ============================================================
# HELPER: EMBED TEXTS WITH OPENAI
# ============================================================

def embed_texts(texts: List[str]) -> List[List[float]]:
    """
    Given a list of strings, returns a list of embedding vectors (list of floats).

    We use OpenAI's embedding endpoint explicitly and then pass the vectors to Chroma.
    This makes the embedding model **explicit** and under our control.

    You can switch model here later (e.g. 'text-embedding-3-small' → '...-large').
    """
    if not texts:
        return []

    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=texts,
    )

    # response.data is a list of objects with `.embedding`
    embeddings = [item.embedding for item in response.data]
    return embeddings


# ============================================================
# MAIN: BUILD / REBUILD THE CHROMA COLLECTION
# ============================================================

def build_symptom_index():
    """
    Main entry point:

    1. Load all structured symptom records.
    2. Build multi-chunk representation for each symptom.
    3. Embed all chunks using OpenAI.
    4. Insert them into a persistent Chroma collection.

    After running this, you will have a searchable vector index on disk, and you
    can later query it from another script (e.g., `symptom_rag_demo.py`) to power
    triage, red-flag checks, and routing decisions.
    """
    # Step 1: load structured symptoms
    symptoms = load_structured_symptoms(STRUCTURED_PATH)

    # Step 2: turn each symptom into multiple chunks
    all_chunks: List[Dict[str, Any]] = []
    for symptom_obj in symptoms:
        chunks = build_chunks_for_symptom(symptom_obj)
        all_chunks.extend(chunks)

    print(f"[+] Built {len(all_chunks)} chunks from {len(symptoms)} symptoms.")

    if not all_chunks:
        print("[!] No chunks found. Did you run symptom_structurer.py first?")
        return

    # Split fields out into parallel arrays for Chroma
    ids = [c["id"] for c in all_chunks]
    documents = [c["text"] for c in all_chunks]
    metadatas = [c["metadata"] for c in all_chunks]

    # Step 3: embed all documents in one go (or batches if you want)
    print("[+] Embedding all chunks with OpenAI...")
    embeddings = embed_texts(documents)
    print("[+] Embedding complete.")

    # Step 4: create / reset the Chroma collection
    # If you want to allow incremental updates later, remove the delete line.
    try:
        chroma_client.delete_collection(COLLECTION_NAME)
        print(f"[i] Existing collection '{COLLECTION_NAME}' deleted (rebuild).")
    except Exception:
        # It's okay if it doesn't exist yet
        pass

    collection = chroma_client.create_collection(name=COLLECTION_NAME)
    print(f"[+] Created Chroma collection: {COLLECTION_NAME}")

    # Step 5: insert all chunks into Chroma
    collection.add(
        ids=ids,
        embeddings=embeddings,
        documents=documents,
        metadatas=metadatas,
    )

    print(f"[✓] Indexed {len(ids)} chunks into collection '{COLLECTION_NAME}'.")
    print(f"[✓] Chroma DB path: {CHROMA_DIR}")

    # Optional: show a sample chunk for sanity check
    sample_id = ids[0]
    sample = collection.get(ids=[sample_id])
    print("\n[Sample stored chunk]")
    print("ID:      ", sample["ids"][0])
    print("Metadata:", sample["metadatas"][0])
    print("Text:\n", sample["documents"][0][:400], "...")


# ============================================================
# SCRIPT ENTRY POINT
# ============================================================

if __name__ == "__main__":
    build_symptom_index()
print("SCRIPT REACHED END")